[".local/share/fonts/Hack"]
    type = "archive"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Hack.zip"
    exact = true
    stripComponents = 0

[".oh-my-zsh"]
    type = "git-repo"
    url = "https://github.com/ohmyzsh/ohmyzsh.git"
    refreshPeriod = "168h"

[".oh-my-zsh/custom/themes/powerlevel10k"]
    type = "git-repo"
    url = "https://github.com/romkatv/powerlevel10k.git"
    refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zshrc.d"]
    type = "archive"
    url = "https://github.com/mattmc3/zshrc.d/archive/HEAD.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
