[".local/share/fonts/Hack"]
    type = "archive"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Hack.zip"
    exact = true
    stripComponents = 0

[".oh-my-zsh/custom/plugins/zshrc.d"]
    type = "archive"
    url = "https://github.com/mattmc3/zshrc.d/archive/HEAD.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
