[tools]
"asdf:neovim" = "ref:stable"
ripgrep = "14.1.0"
rust = "latest"
"cargo:fd-find" = "latest"
"cargo:git-delta" = "latest"
"cargo:tree-sitter-cli" = "latest"
node = "lts"
"npm:@devcontainers/cli" = "latest"
fzf = "latest"
python = "3.12"
kubectl = "latest"

[settings]
# Automatically install missing tools on shell start
asdf_compat = true
jobs = 4

